# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0baa4bae89fb2987f91a910ff5738c1e5f8a79cea8ef8669fc27832e87545ad8c10f1d9059e23136d2f8decd8dcf7e7bbefe77039c19bdf496ada44df26b691b

test:
  secret_key_base: 3fc0f029b135454d5b8b051fb46b6ac3b9a354468ab94acd7ded47753c6c4a331dd4e9b5ebf7a3c62ae772b8115d852a302bd858801e24dbc498798d36d0d517

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
